// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.es');

goog.require('Blockly.Msg');

Blockly.Msg.ACTIVITY_TOOLTIP = "Bloque para una actividad adicional";
Blockly.Msg.ACTOR_TOOLTIP = "Representa cualquier actor.";
Blockly.Msg.BATTERY_GETSAMPLE_TOOLTIP = "Gets the current voltage from the battery.";  // untranslated
Blockly.Msg.BRICKLIGHT = "Luz del ladrillo EV3";
Blockly.Msg.BRICKLIGHT_BLUE = "blue";  // untranslated
Blockly.Msg.BRICKLIGHT_COLOR = "color";
Blockly.Msg.BRICKLIGHT_DOUBLE_FLASH = "doble parpadeo";
Blockly.Msg.BRICKLIGHT_FLASH = "parpadeo";
Blockly.Msg.BRICKLIGHT_GREEN = "verde";
Blockly.Msg.BRICKLIGHT_OFF_TOOLTIP = "Apaga las luces del ladrillo EV3";
Blockly.Msg.BRICKLIGHT_ON = "encendida";
Blockly.Msg.BRICKLIGHT_ON_TOOLTIP = "Enciende las luces del ladrillo EV3";
Blockly.Msg.BRICKLIGHT_ORANGE = "naranja";
Blockly.Msg.BRICKLIGHT_RED = "rojo";
Blockly.Msg.BRICKLIGHT_RESET_TOOLTIP = "Reinicia la luz del EV3. Vuelve a la configuración por defecto: luz verde y parpadear.";
Blockly.Msg.BRICK_TRACK_WIDTH = "distancia entre ruedas";
Blockly.Msg.BRICK_WHEEL_DIAMETER = "diámetro de la rueda";
Blockly.Msg.BUTTON_DO_DELETE = "Borrar";
Blockly.Msg.BUTTON_DO_SHARE = "Compartir";
Blockly.Msg.BUTTON_EMPTY_LIST = "Vaciar lista";
Blockly.Msg.BUTTON_FINISH = "Terminar";
Blockly.Msg.BUTTON_LOAD = "Cargar";
Blockly.Msg.BUTTON_MORE = "more";  // untranslated
Blockly.Msg.BUTTON_REFRESH = "Actualizar";
Blockly.Msg.BUTTON_START = "Try it";  // untranslated
Blockly.Msg.BUTTON_STOP = "Parar";
Blockly.Msg.COLOUR_GETSAMPLE_TOOLTIP = "Obtiene la lectura actual del sensor de color";
Blockly.Msg.COLOUR_TOOLTIP = "Representa el sensor de color del EV3";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_LEFT_MISSING = "¡El motor izquierdo falta en la configuración!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_LEFT_UNREGULATED = "Left motor is not regulated!";  // untranslated
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_MISSING = "¡Falta el motor del puerto indicado!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_RIGHT_MISSING = "¡El motor derecho falta en la configuración!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_RIGHT_UNREGULATED = "Right motor is not regulated!";  // untranslated
Blockly.Msg.CONFIGURATION_ERROR_SENSOR_MISSING = "¡Este sensor no está conectado al puerto!";
Blockly.Msg.CONFIGURATION_ERROR_SENSOR_WRONG = "¡Sensor erróneo conectado al puerto!";
Blockly.Msg.CONNECTION_CHECK = "connection to robot %1 active?";  // untranslated
Blockly.Msg.CONNECTION_CHECK_TOOLTIP = "check if the connection to the robot is active.";  // untranslated
Blockly.Msg.CONNECTION_CONNECT = "Conectar al robot de nombre";
Blockly.Msg.CONNECTION_FROM_ROBOT = "from robot";  // untranslated
Blockly.Msg.CONNECTION_OVER_CHANNEL = "over channel";  // untranslated
Blockly.Msg.CONNECTION_RECEIVED_DATA = "datos recibidos";
Blockly.Msg.CONNECTION_RECEIVE_TOOLTIP = "Espera un mensaje del robot que se declara en la conexión";
Blockly.Msg.CONNECTION_SEND_DATA = "datos enviados a";
Blockly.Msg.CONNECTION_START_TOOLTIP = "Intenta establecer una conexión con otro robot por bluetooth";
Blockly.Msg.CONNECTION_TOOLTIP = "A robot's connection";  // untranslated
Blockly.Msg.CONNECTION_TO_CONNECTION = "to connection";  // untranslated
Blockly.Msg.CONNECTION_TO_ROBOT = "to robot";  // untranslated
Blockly.Msg.CONNECTION_USED_CONNECTION = "Vía conexión";
Blockly.Msg.CONNECTION_WAIT_FOR_CONNECTION = "esperar a la conexión";
Blockly.Msg.CONNECTION_WAIT_TOOLTIP = "Espera a una conexión por bluetooth";
Blockly.Msg.DATATABLE_ACTUALIZATION = "Última actualización";
Blockly.Msg.DATATABLE_BLOCKS = "Bloques";
Blockly.Msg.DATATABLE_CONFIGURATIONS = "configuraciones";
Blockly.Msg.DATATABLE_CONFIGURATION_NAME = "Nombre de configuración";
Blockly.Msg.DATATABLE_CREATED_BY = "Creador";
Blockly.Msg.DATATABLE_CREATED_ON = "Fecha de creación";
Blockly.Msg.DATATABLE_EMPTY_TABLE = "No hay entradas en esta tabla";
Blockly.Msg.DATATABLE_ENTRIES = "entradas";
Blockly.Msg.DATATABLE_FIRST = "<< Primera";
Blockly.Msg.DATATABLE_LAST = "Última >>";
Blockly.Msg.DATATABLE_NEXT = "Siguiente >";
Blockly.Msg.DATATABLE_OF = "de";
Blockly.Msg.DATATABLE_PREVIOUS = "< Anterior";
Blockly.Msg.DATATABLE_PROGRAMS = "programas";
Blockly.Msg.DATATABLE_PROGRAM_NAME = "Nombre del programa";
Blockly.Msg.DATATABLE_SHARED = "Compartido";
Blockly.Msg.DATATABLE_SHARED_WITH = "Compartido con";
Blockly.Msg.DATATABLE_SHOW = "Mostrar";
Blockly.Msg.DATATABLE_SHOWING = "Mostrando";
Blockly.Msg.DATATABLE_TO = "to";  // untranslated
Blockly.Msg.DISPLAY_CLEAR = "borrar pantalla";
Blockly.Msg.DISPLAY_CLEAR_TOOLTIP = "Borra la pantalla.";
Blockly.Msg.DISPLAY_COL = "en columna";
Blockly.Msg.DISPLAY_PICTURE = "imagen";
Blockly.Msg.DISPLAY_PICTURE_EYES_CLOSED = "ojos cerrados";
Blockly.Msg.DISPLAY_PICTURE_EYES_OPEN = "ojos abiertos";
Blockly.Msg.DISPLAY_PICTURE_FLOWERS = "flores";
Blockly.Msg.DISPLAY_PICTURE_GLASSES = "gafas";
Blockly.Msg.DISPLAY_PICTURE_TACHO = "tacómetro";
Blockly.Msg.DISPLAY_PICTURE_TOOLTIP = "Muestra una imagen en la pantalla";
Blockly.Msg.DISPLAY_ROW = "en fila";
Blockly.Msg.DISPLAY_SHOW = "mostrar";
Blockly.Msg.DISPLAY_TEXT = "texto";
Blockly.Msg.DISPLAY_TEXT_TOOLTIP = "Muestra texto en la pantalla";
Blockly.Msg.ENCODER_GETSAMPLE_TOOLTIP = "Obtiene la lectura actual del encoder del motor";
Blockly.Msg.ENCODER_RESET_TOOLTIP = "Reinicia el encoder del motor";
Blockly.Msg.EV3BRICK_TOOLTIP = "Ladrillo EV3";
Blockly.Msg.FOR = "para";
Blockly.Msg.GET = "obtener";
Blockly.Msg.GETSAMPLE_TOOLTIP = "Obtiene la lectura actual del sensor seleccionado";
Blockly.Msg.GYRO_GETSAMPLE_TOOLTIP = "Obtiene la lectura actual del sensor de giroscopio";
Blockly.Msg.GYRO_RESET_TOOLTIP = "Reinicia el sensor de giroscopio";
Blockly.Msg.GYRO_TOOLTIP = "Representa el sensor de giroscopio";
Blockly.Msg.IFELSE_TOOLTIP = "Comprueba la condición en 'si'. Si la condición es verdadera, ejecuta la acción 'entonces'. En caso contrario ejecuta la acción 'si no'.";
Blockly.Msg.IF_TOOLTIP = "Comprueba la condición en 'si'. Si la condición es verdadera, ejecuta la acción 'entonces'.";
Blockly.Msg.INFRARED_GETSAMPLE_TOOLTIP = "Obtiene la lectura actual del sensor de infrarrojos";
Blockly.Msg.INFRARED_TOOLTIP = "Representa el sensor de infrarrojos";
Blockly.Msg.KEY_ISPRESSEDANDRELEASED_TOOLTIP = "¿Se ha pulsado y soltado el botón seleccionado?";
Blockly.Msg.KEY_ISPRESSED_TOOLTIP = "¿Está pulsado el botón seleccionado?";
Blockly.Msg.LIGHT_GETSAMPLE_TOOLTIP = "Gets the current reading from the light sensor.";  // untranslated
Blockly.Msg.LISTS_CREATE_TITLE = "lista";
Blockly.Msg.LOOP = "repetir hasta";
Blockly.Msg.LOOPFOREVER_TOOLTIP = "Repite una acción indefinidamente";
Blockly.Msg.LOOP_COUNT = "número";
Blockly.Msg.LOOP_FOREVER = "repetir indefinidamente";
Blockly.Msg.MENU_ABOUT = "acerca de";
Blockly.Msg.MENU_ATTACH = "adjuntar ...";
Blockly.Msg.MENU_BEGINNER = "principiante";
Blockly.Msg.MENU_BUILDING_INSTRUCTIONS = "building instructions";  // untranslated
Blockly.Msg.MENU_CHANGE = "cambiar ...";
Blockly.Msg.MENU_CHECK = "comprobar";
Blockly.Msg.MENU_CONNECT = "conectar ...";
Blockly.Msg.MENU_DELETE_USER = "borrar usuario ...";
Blockly.Msg.MENU_EDIT = "editar";
Blockly.Msg.MENU_EDIT_TOOLTIP = "editar";
Blockly.Msg.MENU_EV3 = "Preparación del EV3";
Blockly.Msg.MENU_EXPERT = "experto";
Blockly.Msg.MENU_EXPORT_PROG = "export program";  // untranslated
Blockly.Msg.MENU_FAQ = "Preguntas frequentes";
Blockly.Msg.MENU_GENERAL = "ayuda general";
Blockly.Msg.MENU_HELP = "ayuda";
Blockly.Msg.MENU_HELP_TOOLTIP = "ayuda";
Blockly.Msg.MENU_IMPORT_PROG = "import program";  // untranslated
Blockly.Msg.MENU_LANGUAGE = "languages";  // untranslated
Blockly.Msg.MENU_LANGUAGE_TOOLTIP = "languages";  // untranslated
Blockly.Msg.MENU_LIST = "lista ...";
Blockly.Msg.MENU_LIST_CONF = "my configurations ...";  // untranslated
Blockly.Msg.MENU_LIST_PROG = "my programs ...";  // untranslated
Blockly.Msg.MENU_LIST_PROG_EXAMPLES = "example programs ...";  // untranslated
Blockly.Msg.MENU_LOGGING = "accediendo";
Blockly.Msg.MENU_LOG_IN = "iniciar sesión ...";
Blockly.Msg.MENU_LOG_OUT = "cerrar sesión";
Blockly.Msg.MENU_MESSAGE_DOWNLOAD = "Your program has been successfully downloaded.";  // untranslated
Blockly.Msg.MENU_NEW = "nuevo ...";
Blockly.Msg.MENU_PROGRAMMING = "programar con NEPO";
Blockly.Msg.MENU_PROPERTIES = "propiedades";
Blockly.Msg.MENU_ROBOT = "robot";
Blockly.Msg.MENU_ROBOT_STATE_INFO = "información";
Blockly.Msg.MENU_ROBOT_STATE_TOOLTIP = "información del robot";
Blockly.Msg.MENU_ROBOT_TOOLTIP = "robots";
Blockly.Msg.MENU_SAVE = "guardar";
Blockly.Msg.MENU_SAVE_AS = "guardar como ...";
Blockly.Msg.MENU_SHOW_AGAIN = "mostrar nota de bienvenida de nuevo";
Blockly.Msg.MENU_SHOW_CODE = "show code";  // untranslated
Blockly.Msg.MENU_SIM_BACK = "Back";  // untranslated
Blockly.Msg.MENU_SIM_BACK_TOOLTIP = "back to programming editor";  // untranslated
Blockly.Msg.MENU_SIM_DRAW = "Drawing Scene";  // untranslated
Blockly.Msg.MENU_SIM_INFO = "Info";  // untranslated
Blockly.Msg.MENU_SIM_MATH = "Math Scene";  // untranslated
Blockly.Msg.MENU_SIM_RESCUE = "Rescue Scene";  // untranslated
Blockly.Msg.MENU_SIM_ROBERTA = "Roberta Scene";  // untranslated
Blockly.Msg.MENU_SIM_ROBOT_TOOLTIP = "open/close the robot's view";  // untranslated
Blockly.Msg.MENU_SIM_SCENE_TOOLTIP = "change the scene";  // untranslated
Blockly.Msg.MENU_SIM_SIMPLE = "Simple Scene";  // untranslated
Blockly.Msg.MENU_SIM_START_PAUSE = "Start/Pause";  // untranslated
Blockly.Msg.MENU_SIM_STEP = "Step";  // untranslated
Blockly.Msg.MENU_SIM_STOP = "Stop";  // untranslated
Blockly.Msg.MENU_START_BRICK = "run on brick";  // untranslated
Blockly.Msg.MENU_START_SIM = "run in simulation";  // untranslated
Blockly.Msg.MENU_STATE_INFO = "información de estado";
Blockly.Msg.MENU_TOOLBOX = "NEPO-Bloques";
Blockly.Msg.MENU_TOOLBOX_BEGINNER = "NEPO-Bloques principiante";
Blockly.Msg.MENU_TOOLBOX_EXPERT = "NEPO-Bloques experto";
Blockly.Msg.MENU_UPDATE_FIRMWARE = "actualizar firmware";
Blockly.Msg.MENU_USER = "iniciar sesión";
Blockly.Msg.MENU_USER_STATE_TOOLTIP = "información del usuario";
Blockly.Msg.MENU_USER_TOOLTIP = "usuario";
Blockly.Msg.MENU_ZOOM = "zoom";  // untranslated
Blockly.Msg.MENU_ZOOM_IN = "zoom in";  // untranslated
Blockly.Msg.MENU_ZOOM_OUT = "zoom out";  // untranslated
Blockly.Msg.MENU_ZOOM_RESET = "reset zoom";  // untranslated
Blockly.Msg.MESSAGE_CONFIGURATION_DELETED = "La configuración '$' ha sido borrada";
Blockly.Msg.MESSAGE_EDIT_CHECK = "¡Tu programa ha sido comprobado!";
Blockly.Msg.MESSAGE_EDIT_SAVE_CONFIGURATION = "Tu configuración ha sido guardada";
Blockly.Msg.MESSAGE_EDIT_SAVE_CONFIGURATION_AS = "Tu configuración ha sido  guardada como '$'";
Blockly.Msg.MESSAGE_EDIT_SAVE_PROGRAM = "Tu programa ha sido  guardado";
Blockly.Msg.MESSAGE_EDIT_SAVE_PROGRAM_AS = "Tu programa ha sido  guardado como '$'";
Blockly.Msg.MESSAGE_EDIT_START = "Tu programa $ se ejecutará enseguida en el robot";
Blockly.Msg.MESSAGE_FIRMWARE_ERROR = "Hay un conflicto con la versión del firmware de tu robot y Open Roberta Lab. Por favor ponte en contacto con nosotros.";
Blockly.Msg.MESSAGE_INVALID_NAME = "Por favor escribe un nombre correcto. Un nombre correcto ha de comenzar por una letra y solo puede contener letras y números.";
Blockly.Msg.MESSAGE_NOT_AVAILABLE = "No disponible";
Blockly.Msg.MESSAGE_PASSWORD_ERROR = "Algo falló al introducir las dos contraseñas";
Blockly.Msg.MESSAGE_PROGRAM_DELETED = "El programa '$' ha sido borrado";
Blockly.Msg.MESSAGE_RELATION_DELETED = "Una relación del programa '$' ha sido borrada";
Blockly.Msg.MESSAGE_RESTART_ROBOT = "Tu robot solo podrá utilizar el nuevo firmware si reinicias el sistema. No tienes mas que apagar y encender el robot para a continuación conectarlo otra vez a Open Roberta Lab.";
Blockly.Msg.MESSAGE_ROBOT_CONNECTED = "Tu robot $ está conectado";
Blockly.Msg.MESSAGE_ROBOT_FIRMWARE_UPDATE = "La versión del firmware de tu robot es '$'";
Blockly.Msg.MESSAGE_USER_DELETED = "Usuario borrado";
Blockly.Msg.MESSAGE_USER_LOGIN = "Hola '$'";
Blockly.Msg.MESSAGE_USER_LOGOUT = "Has iniciado sesión";
Blockly.Msg.MESSAGE_USER_NEW = "Hola '$'";
Blockly.Msg.MODE = "modo";
Blockly.Msg.MODE_AMBIENTLIGHT = "luz ambiente";
Blockly.Msg.MODE_ANGLE = "ángulo";
Blockly.Msg.MODE_COLOUR = "color";
Blockly.Msg.MODE_DEGREE = "grado";
Blockly.Msg.MODE_DISTANCE = "distancia";
Blockly.Msg.MODE_LIGHT = "luz";
Blockly.Msg.MODE_PRESENCE = "presencia";
Blockly.Msg.MODE_RATE = "ratio";
Blockly.Msg.MODE_RGB = "RGB";
Blockly.Msg.MODE_ROTATION = "rotación";
Blockly.Msg.MODE_SOUND = "sound";  // untranslated
Blockly.Msg.MODE_STATE = "estado";
Blockly.Msg.MOTOR = "motor";
Blockly.Msg.MOTORDIFF_ON_FOR_TOOLTIP = "Pone en marcha el robot con una velocidad determinada y lo detiene después de la distancia indicada.";
Blockly.Msg.MOTORDIFF_ON_TOOLTIP = "Pone en marcha el robot con una velocidad determinada.";
Blockly.Msg.MOTORDIFF_STOP_TOOLTIP = "Detiene el robot.";
Blockly.Msg.MOTORDIFF_TURN_FOR_TOOLTIP = "Gira el robot un número determinado de grados";
Blockly.Msg.MOTORDIFF_TURN_TOOLTIP = "Gira el robot.";
Blockly.Msg.MOTOR_BACKWARD = "hacia atrás";
Blockly.Msg.MOTOR_BIG = "grande";
Blockly.Msg.MOTOR_BIG_TOOLTIP = "Representa un motor grande";
Blockly.Msg.MOTOR_BRAKE = "frenar";
Blockly.Msg.MOTOR_DEGREE = "grado";
Blockly.Msg.MOTOR_DISTANCE = "distancia en cm";
Blockly.Msg.MOTOR_DRIVE = "mover";
Blockly.Msg.MOTOR_FLOAT = "parar";
Blockly.Msg.MOTOR_FOREWARD = "hacia delante";
Blockly.Msg.MOTOR_GETPOWER_TOOLTIP = "Obtiene la potencia actual de este motor.";
Blockly.Msg.MOTOR_LEFT = "izquierdo";
Blockly.Msg.MOTOR_MIDDLE = "medio";
Blockly.Msg.MOTOR_MIDDLE_TOOLTIP = "Representa el motor del medio";
Blockly.Msg.MOTOR_NONE = "ninguno";
Blockly.Msg.MOTOR_ON_FOR_TOOLTIP = "Enciende el motor y lo para después de ejecutar las rotaciones/grados.";
Blockly.Msg.MOTOR_ON_TOOLTIP = "Enciende el motor con una potencia específica.";
Blockly.Msg.MOTOR_OTHER = "otros consumidores de potencia";
Blockly.Msg.MOTOR_PORT = "puerto de motor";
Blockly.Msg.MOTOR_REGULATION = "regulación";
Blockly.Msg.MOTOR_RIGHT = "derecho";
Blockly.Msg.MOTOR_ROTATION = "rotación";
Blockly.Msg.MOTOR_ROTATION_REVERSE = "dirección de la rotación";
Blockly.Msg.MOTOR_SETPOWER_TOOLTIP = "Establece la potencia de este motor.";
Blockly.Msg.MOTOR_SIDE = "lado";
Blockly.Msg.MOTOR_SPEED = "velocidad";
Blockly.Msg.MOTOR_STEER = "steer";  // untranslated
Blockly.Msg.MOTOR_STOP = "para";
Blockly.Msg.MOTOR_STOP_TOOLTIP = "Detiene este motor";
Blockly.Msg.MOTOR_TURN = "gira";
Blockly.Msg.NO = "no";
Blockly.Msg.NXTBRICK_TOOLTIP = "NXT brick.";  // untranslated
Blockly.Msg.OFF = "apagado";
Blockly.Msg.ON = "encendido";
Blockly.Msg.ORA_COMMAND_INVALID = "Comando javascript no válido.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_CONFIGURATION_NOT_FOUND = "No se encontró la configuración del robot en el servidor.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_CONFIGURATION_TRANSFORM_FAILED = "No se pudo transformar la configuración del robot en el lenguaje de programación del robot.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_COMPILE_FAILED = "El programa no se pudo compilar.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_GENERATION_FAILED = "The program could not be generated.";  // untranslated
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_NOT_FOUND = "El programa no se pudo transformar en el lenguaje de programación del robot";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_STORE_FAILED = "No se pudo guardar el programa debido a un error interno.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_TRANSFORM_FAILED = "El programa no se pudo transformar en el lenguaje de programación del robot";
Blockly.Msg.ORA_CONFIGURATION_DELETE_ERROR = "Ha surgido un error al borrar la configuración del robot. Por favor, inténtalo de nuevo.";
Blockly.Msg.ORA_CONFIGURATION_DELETE_SUCCESS = "Configuración borrada";
Blockly.Msg.ORA_CONFIGURATION_ERROR_ID_INVALID = "El nombre de la configuración es un nombre reservado por el sistema. Por favor elige otro nombre e inténtalo de nuevo.";
Blockly.Msg.ORA_CONFIGURATION_GET_ALL_SUCCESS = "Configuración cargada.";
Blockly.Msg.ORA_CONFIGURATION_GET_ONE_ERROR_NOT_FOUND = "No se encontró la configuración del robot en la base de datos.";
Blockly.Msg.ORA_CONFIGURATION_GET_ONE_SUCCESS = "Configuración cargada.";
Blockly.Msg.ORA_CONFIGURATION_SAVE_ERROR = "Error al guardar la configuración.";
Blockly.Msg.ORA_CONFIGURATION_SAVE_ERROR_NOT_SAVED_TO_DB = "Error al guardar la configuración en la base de datos";
Blockly.Msg.ORA_CONFIGURATION_SAVE_SUCCESS = "Configuración guardada";
Blockly.Msg.ORA_OWNER_DOES_NOT_EXIST = "El propietario no existe.";
Blockly.Msg.ORA_PROGRAM_CONFIGURATION_NOT_COMPATIBLE = "Program is not compatible with the configuration";  // untranslated
Blockly.Msg.ORA_PROGRAM_DELETE_ERROR = "Error al borrar el programa. Por favor, inéntalo de nuevo.";
Blockly.Msg.ORA_PROGRAM_DELETE_SUCCESS = "Programa borrado.";
Blockly.Msg.ORA_PROGRAM_ERROR_ID_INVALID = "El nombre del programa es un nombre reservado por el sistema. Por favor elige otro nombre e inténtalo de nuevo.";
Blockly.Msg.ORA_PROGRAM_GET_ALL_SUCCESS = "Programa cargado.";
Blockly.Msg.ORA_PROGRAM_GET_ONE_ERROR_NOT_FOUND = "No se encontró el programa en la base de datos.";
Blockly.Msg.ORA_PROGRAM_GET_ONE_ERROR_NOT_LOGGED_IN = "No has iniciado sesión. Por favor inicia sesión con tu nombre de usuario y contraseña o crea un nuevo usuario";
Blockly.Msg.ORA_PROGRAM_GET_ONE_SUCCESS = "Programa cargado.";
Blockly.Msg.ORA_PROGRAM_IMPORT_ERROR = "This program is not a valid NEPO program and cannot be uploaded!";  // untranslated
Blockly.Msg.ORA_PROGRAM_SAVE_AS_ERROR_PROGRAM_EXISTS = "This program already exists.";  // untranslated
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_NOT_SAVED_TO_DB = "Error al guardar el programa.";
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_NO_WRITE_PERMISSION = "You don't have the permission to modify this program!";  // untranslated
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_OPTIMISTIC_TIMESTAMP_LOCKING = "This program has been changed recently by someone else. You can can save your changes in a new program, choose >save as< !";  // untranslated
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_PROGRAM_TO_UPDATE_NOT_FOUND = "The program could not be found, so it is impossible to update it.";  // untranslated
Blockly.Msg.ORA_PROGRAM_SAVE_SUCCESS = "Programa guardado.";
Blockly.Msg.ORA_PROGRAM_TO_SHARE_DOES_NOT_EXIST = "El programa que quieres compartir no existe.";
Blockly.Msg.ORA_ROBOT_FIRMWAREUPDATE_IMPOSSIBLE = "Ha ocurrido un error al actualizar el firmware de tu robot.";
Blockly.Msg.ORA_ROBOT_FIRMWAREUPDATE_POSSIBLE = "Firmware actualizado.";
Blockly.Msg.ORA_ROBOT_NOT_CONNECTED = "No hay ningún robor conectado. Comprueba si tu robotestá encendido, conéctalo al servidor y entra la contraseña en la pestaña Robot - Conectar en el menu </br> Si tienes algún problema para hacerlo, por favor consulta nuestras páginas de ayuda.";
Blockly.Msg.ORA_ROBOT_NOT_WAITING = "El robot no espera a una orden 'ejecutar'";
Blockly.Msg.ORA_ROBOT_PUSH_RUN = "Tu robot no espera una orden 'ejecutar'";
Blockly.Msg.ORA_SERVER_ERROR = "Error de servidor";
Blockly.Msg.ORA_TOKEN_SET_ERROR_NO_ROBOT_WAITING = "Comprueba si tu robotestá encendido yconéctalo al servidor.</br> Si tienes algún problema para hacerlo, por favor consulta nuestras páginas de ayuda.";
Blockly.Msg.ORA_TOKEN_SET_SUCCESS = "Identificador establecido";
Blockly.Msg.ORA_TOOLBOX_DELETE_ERROR = "An error has occurred while deleting the toolbox, please try it again!";  // untranslated
Blockly.Msg.ORA_TOOLBOX_DELETE_SUCCESS = "Toolbox deleted";  // untranslated
Blockly.Msg.ORA_TOOLBOX_ERROR_ID_INVALID = "Toolbox name is not a valid identifier.";  // untranslated
Blockly.Msg.ORA_TOOLBOX_GET_ALL_SUCCESS = "Toolbox loaded";  // untranslated
Blockly.Msg.ORA_TOOLBOX_GET_ONE_ERROR_NOT_FOUND = "The toolbox could not be found in the database.";  // untranslated
Blockly.Msg.ORA_TOOLBOX_GET_ONE_SUCCESS = "Toolbox loaded";  // untranslated
Blockly.Msg.ORA_TOOLBOX_LOAD_ERROR_NOT_FOUND = "No se encontraron los bloques de NEPO en la base de datos.";
Blockly.Msg.ORA_TOOLBOX_LOAD_SUCCESS = "Cargada la caja de herramientas";
Blockly.Msg.ORA_TOOLBOX_SAVE_ERROR = "An error has occurred while saving the toolbox.";  // untranslated
Blockly.Msg.ORA_TOOLBOX_SAVE_ERROR_NOT_SAVED_TO_DB = "An error error has occurred while saving the configuration in the database.";  // untranslated
Blockly.Msg.ORA_TOOLBOX_SAVE_SUCCESS = "Toolbox saved";  // untranslated
Blockly.Msg.ORA_TOOLBOX_TRANSFORM_ERROR = "Transformation error?";  // untranslated
Blockly.Msg.ORA_USER_CREATE_ERROR_MISSING_REQ_FIELDS = "Desaparecidos los campos necesarios";
Blockly.Msg.ORA_USER_CREATE_ERROR_NOT_SAVED_TO_DB = "Error al almacenar el usuario";
Blockly.Msg.ORA_USER_CREATE_SUCCESS = "El usuario ha sido creado con éxito";
Blockly.Msg.ORA_USER_DELETE_ERROR_ID_NOT_FOUND = "Error al borrar un usuario.";
Blockly.Msg.ORA_USER_DELETE_ERROR_NOT_DELETED_IN_DB = "Error al borrar un usuario en la base de datos.";
Blockly.Msg.ORA_USER_DELETE_SUCCESS = "El usuario ha sido borrado con éxito.";
Blockly.Msg.ORA_USER_EMAIL_ONE_ERROR_USER_NOT_EXISTS_WITH_THIS_EMAIL = "This email address is unknown, maybe you have spelled it wrong!";  // untranslated
Blockly.Msg.ORA_USER_GET_ALL_SUCCESS = "Usuarios cargados.";
Blockly.Msg.ORA_USER_GET_ONE_ERROR_ID_OR_PASSWORD_WRONG = "Ha ocurrido un eror al iniciar sesión. ¿Has ingresado el nombre de usuario y la contraseña correctamente?</br> ¡Inténtalo de nuevo!";
Blockly.Msg.ORA_USER_GET_ONE_SUCCESS = "Acceso conseguido";
Blockly.Msg.ORA_USER_TO_SHARE_DOES_NOT_EXIST = "El usuario con el que quieres compartir no existe.</br>¡Inténtalo de nuevo!";
Blockly.Msg.ORA_USER_TO_SHARE_SAME_AS_LOGIN_USER = "No puedes compartir un archivo contigo mismo.";
Blockly.Msg.PLAY = "reproducir";
Blockly.Msg.PLAY_DURATION = "duración";
Blockly.Msg.PLAY_FILE = "archivo";
Blockly.Msg.PLAY_FILE_TOOLTIP = "Reproduce un archivo de sonido.";
Blockly.Msg.PLAY_FREQUENZ = "frecuencia";
Blockly.Msg.PLAY_GETVOLUME_TOOLTIP = "Obtiene el volumen actual";
Blockly.Msg.PLAY_SETVOLUME_TOOLTIP = "Configura el volumen.";
Blockly.Msg.PLAY_TONE = "tono";
Blockly.Msg.PLAY_TONE_TOOLTIP = "Reproduce un tono";
Blockly.Msg.PLAY_VOLUME = "volumen";
Blockly.Msg.POPUP_ABOUT_JOIN = "quiero ayudar";
Blockly.Msg.POPUP_ABOUT_TEXT = "Open Roberta Lab es un entorno de programación integrado basado en la nube que permite a niñas,  niños y adolescentes programar de un modo sencillo robots Lego Mindstorms EV3. Esta plataforma es totalmente de código abierto, así que la participación en ella es bienvenida. Tanto el software como las herramientas de desarrollo en código abierto están disponibles en los servidores de Fraunhofer.";
Blockly.Msg.POPUP_ABOUT_TEXT_DEV = "Open Roberta Lab es una plataforma de programación en código abierto desarrollada por Fraunhofer IAIS a iniciativa de <a href='http://www.roberta-home.de/'>»Roberta – Learning with Robots«</a>";
Blockly.Msg.POPUP_ABOUT_TEXT_GOOG = "Open Roberta se inició en colaboración con Google Germany para reducir las barreras para alumnos, profesores y escuelas que usan robots para educación. Open Roberta esta financiada por Google.org (2 14 - 2.15) con 1M de Euros.</a>";
Blockly.Msg.POPUP_ATTENTION = "Atención";
Blockly.Msg.POPUP_BEFOREUNLOAD = "Tienes cambios sin guardar en tu programa o configuración. Accede a tu cuenta y guarda tu programa o configuración.";
Blockly.Msg.POPUP_BEFOREUNLOAD_LOGGEDIN = "Tienes cambios sin guardar en tu programa o configuración.";
Blockly.Msg.POPUP_CANCEL = "Cancelar";
Blockly.Msg.POPUP_CHANGE_PASSWORD = "change password ...";  // untranslated
Blockly.Msg.POPUP_CONFIRM_DELETE_CONFIGURATION = "¿Estás seguro de querer borrar esta configuración?";
Blockly.Msg.POPUP_CONFIRM_DELETE_PROGRAM = "¿Estás seguro de querer borrar este programa?";
Blockly.Msg.POPUP_CONFIRM_UPDATE_FIRMWARE = "Hay disponible una nueva versión de firmware para tu robot. Puedes intentar ejecutar programas con la versión antigua, pero la mejor opción es actualizar tu robot ahora. Lo único que tienes que hacer es hacer clic sobre >>Actualiza ahora<< y reiniciar el robot a continuación.";
Blockly.Msg.POPUP_CONTINUE = "continue anyway";  // untranslated
Blockly.Msg.POPUP_DO_UPDATE_FIRMWARE = "Actualizar ahora";
Blockly.Msg.POPUP_EMAIL = "Correo electrónico";
Blockly.Msg.POPUP_EMAIL_SEND = "Send now";  // untranslated
Blockly.Msg.POPUP_NAME = "Nombre";
Blockly.Msg.POPUP_NEW_PASSWORD = "New Password";  // untranslated
Blockly.Msg.POPUP_NEW_RELEASE = "Version beta 1.4 <ul class='NonIcon'><li>Create one program for the real robot <strong>and</strong> for the simulated robot</li><li>Update blockly for better performance and zoom function</li></ul>";  // untranslated
Blockly.Msg.POPUP_OLD_PASSWORD = "Old Password";  // untranslated
Blockly.Msg.POPUP_PASSWORD = "Contraseña";
Blockly.Msg.POPUP_PASSWORD_RECOVERY = "reset password ...";  // untranslated
Blockly.Msg.POPUP_PROGRAM_TERMINATED_UNEXPECTED = "The execution of the program on the robot has terminated unexpectedly!";  // untranslated
Blockly.Msg.POPUP_REGISTER_USER = "Register now";  // untranslated
Blockly.Msg.POPUP_RELEASE = "Version beta 1.3.2 <ul class='NonIcon'><li>Fix timestamp bug for save program</li></ul>Version beta 1.3.1 <ul class='NonIcon'><li>Spanish available now!</li><li>Fixed bugs</li></ul>Version beta 1.3.0 <ul class='NonIcon'><li>Simulate a robot!</li><li>Share your program with a friend</li><li>Update the robots firmware Over-the-Air</li><li>USB cabel support for Chromebooks</li><li>Fixed many more bugs</li></ul></br>";  // untranslated
Blockly.Msg.POPUP_REPEAT_PASSWORD = "Repetir contraseña";
Blockly.Msg.POPUP_ROBOT_BATTERY = "Voltaje";
Blockly.Msg.POPUP_ROBOT_NAME = "Nombre";
Blockly.Msg.POPUP_ROBOT_NOT_CONNECTED = "Primero tienes que establecer una conexión con tu robot.";
Blockly.Msg.POPUP_ROBOT_STATE = "Estado";
Blockly.Msg.POPUP_ROBOT_STATE_BUSY = "ocupado";
Blockly.Msg.POPUP_ROBOT_STATE_DISCONNECTED = "desconectado";
Blockly.Msg.POPUP_ROBOT_STATE_WAIT = "espera";
Blockly.Msg.POPUP_ROBOT_SYSTEM = "System";  // untranslated
Blockly.Msg.POPUP_ROBOT_WAIT = "Tiempo de espera";
Blockly.Msg.POPUP_SHARE_READ = "LEER";
Blockly.Msg.POPUP_SHARE_WITH = "Nombre";
Blockly.Msg.POPUP_SHARE_WRITE = "ESCRIBIR";
Blockly.Msg.POPUP_STARTUP_COOKIES = "We use cookies to personalise content and to analyse our traffic.";  // untranslated
Blockly.Msg.POPUP_STARTUP_DETAILS = "Show details.";  // untranslated
Blockly.Msg.POPUP_STARTUP_HELP = "Do you need help?";  // untranslated
Blockly.Msg.POPUP_STARTUP_HIDE = "Okay, don't show this window again and remember my choice.";  // untranslated
Blockly.Msg.POPUP_STARTUP_NEW = "What's new?";  // untranslated
Blockly.Msg.POPUP_STARTUP_TITLE = "Welcome";  // untranslated
Blockly.Msg.POPUP_TOUR = "take a tour";  // untranslated
Blockly.Msg.POPUP_USERNAME = "Nombre de usuario";
Blockly.Msg.POPUP_USERNAME_LOGOFF = "No has iniciado sesión.";
Blockly.Msg.POPUP_VALUE = "Valor";
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "hacer algo";
Blockly.Msg.PROCEDURES_TITLE = " procedimiento";
Blockly.Msg.PROCEDURES_VARIABLES_ERROR = "Error: este bloque solo se puede usar dentro de '";
Blockly.Msg.PROCEDURES_VARIABLES_LOOP_ERROR = "Error: este bloque solo se puede usar dentro de un bucle que declara";
Blockly.Msg.SEND_DATA = "data to send";  // untranslated
Blockly.Msg.SENSOR_BATTERY = "voltage in mV";  // untranslated
Blockly.Msg.SENSOR_COLOUR = "sensor de color";
Blockly.Msg.SENSOR_ENCODER = "encoder";
Blockly.Msg.SENSOR_GET_MODE = "obtener modo";
Blockly.Msg.SENSOR_GET_SAMPLE = "obtener valor";
Blockly.Msg.SENSOR_GYRO = "giroscopio";
Blockly.Msg.SENSOR_INFRARED = "sensor de infrarrojos";
Blockly.Msg.SENSOR_IS_PRESSED = "pulsado?";
Blockly.Msg.SENSOR_KEY = "botón";
Blockly.Msg.SENSOR_KEY_ANY = "cualquier";
Blockly.Msg.SENSOR_KEY_DOWN = "abajo";
Blockly.Msg.SENSOR_KEY_ENTER = "intro";
Blockly.Msg.SENSOR_KEY_ESCAPE = "escape";
Blockly.Msg.SENSOR_KEY_LEFT = "izquierda";
Blockly.Msg.SENSOR_KEY_RIGHT = "derecha";
Blockly.Msg.SENSOR_KEY_UP = "arriba";
Blockly.Msg.SENSOR_LIGHT = "light sensor";  // untranslated
Blockly.Msg.SENSOR_MS_TIMER = "en ms";
Blockly.Msg.SENSOR_PRESSED = " (pulsado)";
Blockly.Msg.SENSOR_RESET = "reiniciar";
Blockly.Msg.SENSOR_RESET_II = "";  // untranslated
Blockly.Msg.SENSOR_SET_MODE = "configurar modo";
Blockly.Msg.SENSOR_SOUND = "sound sensor";  // untranslated
Blockly.Msg.SENSOR_TIME = "tiempo de espera";
Blockly.Msg.SENSOR_TIMER = "temporizador";
Blockly.Msg.SENSOR_TOUCH = "sensor de contacto";
Blockly.Msg.SENSOR_ULTRASONIC = "sensor de ultrasonidos";
Blockly.Msg.SENSOR_WAIT_PRESSED = "pulsado";
Blockly.Msg.SENSOR_WAIT_PRESSED_RELEASED = "pulsado o liberado";
Blockly.Msg.SERVER_NOT_AVAILABLE = "The Open Roberta Lab is currently not available. </br> Please check your internet connection and try to reload this website. If the problem persists, please don't hasitate to contact us via mail:</br>roberta-zentrale@iais.fraunhofer.de";  // untranslated
Blockly.Msg.SET = "set";  // untranslated
Blockly.Msg.SIM_BLOCK_NOT_SUPPORTED = "Unfortunately you can not use this block in the simulation!";  // untranslated
Blockly.Msg.SIM_CONFIGURATION_WARNING_SENSOR_MISSING = "This sensor is not in the configuration! The behavior of the program on the real robot will be different than expected!";  // untranslated
Blockly.Msg.SIM_CONFIGURATION_WARNING_WRONG_INFRARED_SENSOR_PORT = "The infrared sensor is not connected in the configuration! The behavior of the program on the real robot will be different than expected, please check the robot configuration!";  // untranslated
Blockly.Msg.SIM_CONFIGURATION_WARNING_WRONG_SENSOR_PORT = "In this block you have used a wrong sensor port! The behavior of the program on the real robot will be different than expected, please check the robot configuration!";  // untranslated
Blockly.Msg.SOUND_GETSAMPLE_TOOLTIP = "Gets the current reading from the sound sensor.";  // untranslated
Blockly.Msg.START = "Inicio del programa";
Blockly.Msg.START_ACTIVITY = "actividad";
Blockly.Msg.START_ACTIVITY_TOOLTIP = "Inicia una actividad adicional";
Blockly.Msg.START_PROGRAM = "Inicio del programa";
Blockly.Msg.START_PROGRAM_DEBUG = "show sensor data";  // untranslated
Blockly.Msg.START_TOOLTIP = "Punto de inicio del programa principal";
Blockly.Msg.TAB_CONFIGURATION = "Configuración del robot";
Blockly.Msg.TAB_PROGRAM = "Programa";
Blockly.Msg.TAB_SIMULATION = "Simulación";
Blockly.Msg.TIMER_GETSAMPLE_TOOLTIP = "Obtiene la lectura actual del temporizador";
Blockly.Msg.TIMER_RESET_TOOLTIP = "Reinicia el temporizador";
Blockly.Msg.TOOLBOX_ACTION = "Acción";
Blockly.Msg.TOOLBOX_COLOUR = "Colores";
Blockly.Msg.TOOLBOX_COMMUNICATION = "Mensajes";
Blockly.Msg.TOOLBOX_CONTROL = "Control";
Blockly.Msg.TOOLBOX_DECISION = "Decisiones";
Blockly.Msg.TOOLBOX_DISPLAY = "Pantalla";
Blockly.Msg.TOOLBOX_DRIVE = "Drive";  // untranslated
Blockly.Msg.TOOLBOX_GLOBAL_VARIABLE = "Variables globales";
Blockly.Msg.TOOLBOX_LIGHT = "Luz";
Blockly.Msg.TOOLBOX_LIST = "Listas";
Blockly.Msg.TOOLBOX_LOGIC = "Lógica";
Blockly.Msg.TOOLBOX_LOOP = "Bucles";
Blockly.Msg.TOOLBOX_LOOP_VARIABLE = "Variables de bucle";
Blockly.Msg.TOOLBOX_MATH = "Matemáticas";
Blockly.Msg.TOOLBOX_MOVE = "Mover";
Blockly.Msg.TOOLBOX_PROCEDURE = "Funciones";
Blockly.Msg.TOOLBOX_SENSOR = "Sensores";
Blockly.Msg.TOOLBOX_SOUND = "Sonidos";
Blockly.Msg.TOOLBOX_TEXT = "Texto";
Blockly.Msg.TOOLBOX_VARIABLE = "Variables";
Blockly.Msg.TOOLBOX_WAIT = "Espera";
Blockly.Msg.TOUCH_ISPRESSED_TOOLTIP = "¿Está el sensor de contacto pulsado?";
Blockly.Msg.TOUCH_TOOLTIP = "¿Está el sensor de contacto pulsado?";
Blockly.Msg.TOUR1_DESCRIPTION00 = "next";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION01 = "Welcome,<br>click on  »next« and start a tour through the Open Roberta Lab.<br>I'll show you how you can program your robot with NEPO.<br>You can end this tour all the time with a click on »X« in the right upper corner.";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION02 = "The menu ;-)";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION03 = "Here you can find everything you need to program the robot!<br><span class='typcn typcn-document-text'></span> Save and load programs<br><span class='typcn typcn-Roberta'></span> Connect your robot to the Open Roberta Lab<br><span class='typcn typcn-lightbulb'></span> Help for all kinds of problems<br><span class='typcn typcn-user'></span>Everything about user accounts, e.g. login or logoff";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION04 = "Click here and switch to the robot configuration";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION05 = "You can adapt the robot configuration later,<br>if you've constructed another robot.<br>If you don't have a robot and want to test your program in the simulation <br>this configuration is applied.";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION06 = "Click here and switch back to the programming area!";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION07 = "The toolbox.<br>Here you can find all programming blocks.";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION08 = "Each program starts with the program-start-block«.<br>Further programming blocks, which the robot should execute, should be attached to this block.<br>Just drag'n drop the desired block right under the start block.";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION09 = "Here you find some shortcuts!<br>From left to right:<br><span class='typcn typcn-media-play'></span> Click here to execute the program on the real robot<br><span class='typcn typcn-media-play-outline'></span> Click here to start the robot in the simulation<br><span class='typcn typcn-cloud-storage'></span> Save your program, but before that you need to sign in<br><span class='typcn typcn-zoom'></span> Click here and zoom in on the blocks, if you want to<br><span class='typcn typcn-archive'></span> The trashcan! Just move blocks into the trashcan and they will be deleted.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Attention: You cannot recover blocks once they are deleted!<br>";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION10 = "Click on »Action«";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION11 = "Click and create the block in the workspace";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION12 = "Now drag'n drop the new block just below the start-program-block so that they are connected";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION13 = "Now test your program in the simulation!";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION14 = "Just a moment!";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION15 = "Perfect,<br>your robot is driving 20 cm forward,<br>this is what you have programmed!";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION16 = "Bye and have fun trying out more!";  // untranslated
Blockly.Msg.ULTRASONIC_GETSAMPLE_TOOLTIP = "Obtiene la lectura actual del sensor ultrasónico.";
Blockly.Msg.ULTRASONIC_TOOLTIP = "Representa el sensor de ultrasonidos del EV3";
Blockly.Msg.VALIDATION_FIELD_REQUIRED = "This field cannot be empty!";  // untranslated
Blockly.Msg.VALIDATION_PASSWORD_MIN_LENGTH = "Password min length is 6!";  // untranslated
Blockly.Msg.VALIDATION_SECOND_PASSWORD_EQUAL = "The two passwords must be equal!";  // untranslated
Blockly.Msg.VALIDATION_TOKEN_LENGTH = "Token length is 8 characters!";  // untranslated
Blockly.Msg.VALIDATION_VALID_EMAIL_ADDRESS = "Please enter a valid email address!";  // untranslated
Blockly.Msg.VARIABLES_CREATE_TITLE = "Crear";
Blockly.Msg.VARIABLES_CREATE_WITH = "con";
Blockly.Msg.VARIABLES_GLOBAL_DECLARE_TOOLTIP = "Declara una variable global";
Blockly.Msg.VARIABLES_LOCAL_DECLARE_TOOLTIP = "Declara una variable local";
Blockly.Msg.VARIABLES_TITLE = "variable";
Blockly.Msg.VARIABLES_TYPE_ARRAY_BOOLEAN = "Lista Booleana";
Blockly.Msg.VARIABLES_TYPE_ARRAY_COLOUR = "Lista Color";
Blockly.Msg.VARIABLES_TYPE_ARRAY_CONNECTION = "List Connection";  // untranslated
Blockly.Msg.VARIABLES_TYPE_ARRAY_NUMBER = "Lista Número";
Blockly.Msg.VARIABLES_TYPE_ARRAY_STRING = "Lista Cadena";
Blockly.Msg.VARIABLES_TYPE_BOOLEAN = "Booleana";
Blockly.Msg.VARIABLES_TYPE_COLOUR = "Color";
Blockly.Msg.VARIABLES_TYPE_CONNECTION = "Conexión";
Blockly.Msg.VARIABLES_TYPE_NUMBER = "Número";
Blockly.Msg.VARIABLES_TYPE_STRING = "Cadena";
Blockly.Msg.WAIT = "esperar";
Blockly.Msg.WAIT_FOREVER = "indefinidamente";
Blockly.Msg.WAIT_FOR_TOOLTIP = "Espera a los valores de los sensores";
Blockly.Msg.WAIT_OR = "o esperar a";
Blockly.Msg.WAIT_TOOLTIP = "espera hasta que la condición sea verdadera";
Blockly.Msg.WAIT_UNTIL = "esperar hasta";
Blockly.Msg.YES = "sí";
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;